### ISSUE TITLE
NIOTransportServices

### ISSUE THREAD

**Issue by oliverepper** [swift-server-community/APNSwift#120]
Hi!

Would it be possible to support a `NIOTSEventloopGroup` instead of the `MultiThreadedEventLoopGroup` for the `APNSwiftConnection`?

greetings
Oliver

**Comment by kylebrowning** [comment]
I *think* we might be moving towards AsyncHTTPClient which uses it's own setup, but what's the use care for it?

**Comment by oliverepper** [comment]
Well as far as I understand using NIOTSEventLoopGroup and thus NetworkFramework has better support on Apple platforms (read: more knowledge about energy efficiency measurements). So I guess one would benefit if you want to run a push-server on a non-server setup (iPhone, iPad).

**Comment by kylebrowning** [comment]
Interesting. I wonder if there's a way to support both. Probably

**Comment by kylebrowning** [comment]
@oliverepper It looks like moving this over to ASYNCHttpRequest will resolve this issue.

**Comment by kylebrowning** [comment]
Closing as this fixes it, https://github.com/swift-server-community/APNSwift/pull/130
