### ISSUE TITLE
Can't send "content-available" on its own

### ISSUE THREAD

**Issue by marekpridal** [swift-server-community/APNSwift#126]
This issue was [originally reported in Vapor project](https://github.com/vapor/apns/issues/39) but based on discussion it should be probably resolved inside this repo. There is a workaround which requires creating payload from raw data.

**Comment by DanSessions** [comment]
Having the same issue. @marekpridal, can you share the code for the workaround? Can't get it working.

**Comment by kylebrowning** [comment]
Hmm this seems to be working for me, would love to see the raw payload so I can make changes for an interface if necesary

**Comment by kylebrowning** [comment]
```swift
        let payload = APNSPayload(hasContentAvailable: true)
        let acme = AcmeNotification(acme1: "hey", acme2: 2, aps: payload)
        try! await req.apns.client.send(acme, pushType: .background, to: dt, priority: 5)
```

here's the code that worked for me. Going to close this issue, but please re-open if its still an issue for you
