### ISSUE TITLE
README is outdated.

### ISSUE THREAD

**Issue by genkernel** [swift-server-community/APNSwift#145]
**Is your feature request related to a problem? Please describe.**
Example code snippets from README do not compile.

**Describe the solution you'd like**
Updated README with recent syntax.

**Describe alternatives you've considered**
Void

**Additional context**
I dove into the source code and came up with below snippet that compiles and works.
By submitting this Issue I'm looking to:
  - have somebody to confirm that my code is OK or suggest a better solution.
  - have README.md file updated with code snippets that compile.

```
let auth = APNSwiftConfiguration.AuthenticationMethod.jwt(
            key: try ECDSAKey.private(filePath: ".../path-to/AuthKey.p8"),
            keyIdentifier: JWKIdentifier(string: "keyId-value"),
            teamIdentifier: "teamId-value"
        )
        
        let config = APNSwiftConfiguration(
            authenticationMethod: auth,
            topic: appBundleId,
            environment: isProduction ? .production : .sandbox,
            logger: nil,
            timeout: .seconds(10)
        )
        
        let eventLoopGroup = MultiThreadedEventLoopGroup(numberOfThreads: 1)

        let conn = try APNSwiftConnection.connect(
            configuration: config,
            on: eventLoopGroup.any()
        ).wait()

        // Use `send()` methods on `conn` to send push notifications.
```

Thanks for building this!

**Comment by kylebrowning** [comment]
hmm, what part of the Getting Started section didn't work for you?

**Comment by genkernel** [comment]
All of it.
I was not able to compile code from Getting Started section.

It looks like most classes were renamed, e.g. 
```
APNSConfiguration ---> APNSwiftConfiguration
APNSClient ---> APNSwiftConnection
```

and many functions changed:
```
// function loadFrom not available anymore
privateKey: try .loadFrom(filePath: "/Users/kylebrowning/Documents/AuthKey_9UC9ZLQ8YW.p8"),
// what used to be
APNSClient(configuration: apnsConfig)
// I found to be:
try APNSwiftConnection.connect(
            configuration: config,
            on: eventLoopGroup.any()
        )
```

Are you able to compile a code from Getting Started section?

**Comment by kylebrowning** [comment]
Well, cloning the project, using the alpha tag, opening Package.swift and running that seems to work, but we've just gone through an overall in main so give me a few hours to get a new Reademe up

**Comment by kylebrowning** [comment]
If you're trying to use 4.0.0 that readme is here, https://github.com/swift-server-community/APNSwift/tree/4.0.0

**Comment by kylebrowning** [comment]
Try this. https://github.com/swift-server-community/APNSwift/pull/151

**Comment by kylebrowning** [comment]
And recheck out the main branch.
