### ISSUE TITLE
Need to extend PushType to support LiveActivities

### ISSUE THREAD

**Issue by watling** [swift-server-community/APNSwift#165]
I believe the pushType enum needs to include a new element for liveactivities

extension APNSwiftConnection {
    public enum PushType: String {
        case alert
        case background
        case mdm
        case voip
        case fileprovider

        **  case liveactivity **

    }
}

**Comment by kylebrowning** [comment]
It does include it. 

https://github.com/swift-server-community/APNSwift/blob/main/Sources/APNSwift/APNSPushType.swift#L26

**Comment by watling** [comment]
Sorry, I wasn't aware of the alpha builds - Thanks.
