### ISSUE TITLE
What does the readme in this repo apply to?

### ISSUE THREAD

**Issue by chrisschlitt** [swift-server-community/APNSwift#175]
I've followed the instructions to add the package to my swift project with:
```
dependencies: [
    .package(url: "https://github.com/swift-server-community/APNSwift.git", from: "4.0.0"),
]
```
But that gives me what seems to be an entirely different package with many missing features. I have the ability to create a connection, but no ability to create a client or call `sendLiveActivityNotification` like it shows in this readme.

Am I missing something?

**Comment by kylebrowning** [comment]
@chrisschlitt Sorry readme seems to be assuming you are running 5.0.0+, which is safe to run in prod! I am. Just currently making sure the API's have had time to bake before solidifying them.

**Comment by chrisschlitt** [comment]
Ohhhhhhh, I'm so sorry, still having my coffee today. This is fantastic, and thank you for the quick response! I'll bump my package version.
Thanks for all the hard work here!
