### ISSUE TITLE
Keep failure reason PUBLIC

### ISSUE THREAD

**Issue by ihamadfuad** [swift-server-community/APNSwift#176]
/// The error code indicating the reason for the failure.
public let reason: ErrorReason?

This property found public in `main` branch however in 5x.x is private!

I use this property to remove unregistered deviceTokens or other reason might occur to offload many failed push requests which all of us may already know how much time will save us to execute queues

Please keep it public in all branches

**Comment by kylebrowning** [comment]
Resolved in 5.0.0-beta.5

**Comment by ihamadfuad** [comment]
Thank you very much indeed, Kyle.
