### ISSUE TITLE
HOW to send raw custom payload

### ISSUE THREAD

**Issue by SupaBasti** [swift-server-community/APNSwift#179]
the README says it would be able to send Data as raw payload, but I do not find the proper API. There is one send method with takes an APNSRequest as parameter with a message property conforming to APNSMessage protocol.

However, often the custom payload has different properties and thus cannot be represented by a struct with fix property types.

So, how can I add a custom Payload dictionary to an APNSMessage?

**Comment by kylebrowning** [comment]
@SupaBasti Can you extend APNSMessage and send that?

```swift
public struct MyCustomMessage<Payload: Encodable & Sendable>: APNSMessage, Sendable {

**Comment by kylebrowning** [comment]
I suppose not. let me take a look at the API

**Comment by kylebrowning** [comment]
Can you give me an example of what you're trying to accomplish ?

**Comment by SupaBasti** [comment]
I found a workaround: I just send my custom payload as [String:String] dictionary instead of [String: Any]. Thus I can put it directly into the payload property. All fine. Thanks
