### ISSUE TITLE
The APNSwift 5.0.0 has no raw API and semantically safe API, only supported the  safest API

### ISSUE THREAD

**Issue by wangzhizhou** [swift-server-community/APNSwift#184]
The APNSwift 5.0.0 has no raw API supported as the readme.md descripted! How can I migrate from 4.0.0 to 5.0.0

Maybe you should update the readme.md or supply an migration guide from 4.0.0 to 5.0.0

![image](https://github.com/swift-server-community/APNSwift/assets/8174538/731526fe-2895-4920-973b-b52dbcd66650)

- RawAPI
![image](https://github.com/swift-server-community/APNSwift/assets/8174538/ef4b4efb-77f1-40b7-b93c-ff69ced0f7f2)

- Semantically safe API
![image](https://github.com/swift-server-community/APNSwift/assets/8174538/1ae1c9ad-68e4-4a77-8743-e76457e511ba)

**Comment by kylebrowning** [comment]
Sorry the readme is out of date, its been updated

**Comment by wangzhizhou** [comment]
We can use the [AnyCodable](https://github.com/flight-school/anycodable.git)
