### ISSUE TITLE
Increase swift-crypto versions range

### ISSUE THREAD

**Issue by NikolayJuly** [swift-server-community/APNSwift#186]
**Is your feature request related to a problem? Please describe.**
swift-crypto released 3.0 in September, and now I can't updated to latest, because of dependency on APNSwift

**Describe the solution you'd like**
`.package(url: "https://github.com/apple/swift-crypto.git", "1.0.0"..<"4.0.0"),`

**Comment by kylebrowning** [comment]
Good call, will do so soon.
