### ISSUE TITLE
TLS authentication is not working

### ISSUE THREAD

**Issue by hakarim740-com-ra** [swift-server-community/APNSwift#208]
**Describe the bug**
When using `tls` authentication method I receive `MissingProviderToken` error.

**Expected behavior**
The push is supposed to be sent successfully.

**Screenshots**

**Platform:**
 - OS: macOS
 - Version 14.5

**Platform:**
 - OS: Ubuntu
 - Version 22.04

**Comment by hakarim740-com-ra** [comment]
> Can you share your config?

```swift
let apnsConfig = APNSClientConfiguration(
    authenticationMethod: .tls(
        privateKey: .file(".../voip_apns_key.p12.pem"),
        certificateChain: [ ]),
    environment: .development
)

```

**Comment by kylebrowning** [comment]
`.file` isn't something supported by APNS, can you share that part of your code?

**Comment by hakarim740-com-ra** [comment]
> `.file` isn't something supported by APNS, can you share that part of your code?

It is available in `NIOSSLCertificateSource` enum

**Comment by kylebrowning** [comment]
Gotcha, I just tried this and it worked for me, I had to make my own group though to get it to work.

```swift
        let group = MultiThreadedEventLoopGroup(numberOfThreads: 1)
        let client = APNSClient(
            configuration: .init(
                authenticationMethod: .tls(
                    privateKey: .privateKey(try! .init(file: "/Users/kyle/Developer/Certificates.pem", format: .pem)),
                    certificateChain: [
                        .certificate(try! .init(file: "/Users/kyle/Developer/Certificates.pem", format: .pem))
                    ]
                ),
                environment: .development
            ),
            eventLoopGroupProvider: .shared(group),
            responseDecoder: JSONDecoder(),
            requestEncoder: JSONEncoder()
        )
```

**Comment by hakarim740-com-ra** [comment]
> Gotcha, I just tried this and it worked for me, I had to make my own group though to get it to work.
> 
> ```swift
>         let group = MultiThreadedEventLoopGroup(numberOfThreads: 1)
>         let client = APNSClient(
>             configuration: .init(
>                 authenticationMethod: .tls(
>                     privateKey: .privateKey(try! .init(file: "/Users/kyle/Developer/Certificates.pem", format: .pem)),
>                     certificateChain: [
>                         .certificate(try! .init(file: "/Users/kyle/Developer/Certificates.pem", format: .pem))
>                     ]
>                 ),
>                 environment: .development
>             ),
>             eventLoopGroupProvider: .shared(group),
>             responseDecoder: JSONDecoder(),
>             requestEncoder: JSONEncoder()
>         )
> ```

Providing the `certificateChain` solved it for me.

Thanks.
