### ISSUE TITLE
Arguing for adding support for content-available in alert notifications

### ISSUE THREAD

**Issue by Frizlab** [swift-server-community/APNSwift#214]
**Is your feature request related to a problem? Please describe.**
Yes.
My goal is to write a conversation solution (among other).
When I was in another company, when we sent a push for a new message, we used to use a `content-available` push, to be called in `didReceiveRemoteNotification` in the iOS app.
I’d like to do the same, but APNSwift does not allow alert notifications w/ `content-available`.

**Describe the solution you'd like**
Add a `contentAvailable` argument to `APNSAlertNotification`.

**Describe alternatives you've considered**
- Send a silent notification _in addition to_ the alert notification. This has the advantage of making it possible to coalesce the potential background updates. This would have to be in conjonction with the other alternative considered:
- Use the user notification delegate and `willPresent`. This works only when the app is in the foreground. The app won’t be launched if it is not in memory anymore, nor even if it is in the background.

**Additional context**
I understand Apple seems to not want the `content-available` key to be used alongside an alert, but really, it works… (I have tested.)

What do you think?

**Comment by kylebrowning** [comment]
Its been suggested already https://github.com/swift-server-community/APNSwift/pull/209

I would think its safer to not support it as if something breaks with APple's side, people will using this library will come here asking why.

That being said you can write a custom version of the Alert yourself in your own library and use it.
